# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'
    branches:    
      - master         # Push events on master branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    env:
      targetName: HelloActions-Qt

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:   
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      
    - name: Install Qt
      run: |
        brew update > /dev/null
        brew install qt5 > /dev/null
        brew install openssl > /dev/null
        export PATH=/usr/local/opt/qt5/bin/:$PATH
        qmake -v
    
    - name: Git Clon
      run: |
        git clone --depth 1 https://github.com/uglide/RedisDesktopManager.git rdm

    - name: act
      run: |
        DIR=`pwd`
        TAG="202001"
        cd $DIR/rdm/src/resources
        cp Info.plist.sample Info.plist
        sed -i "" "s/0.0.0/$TAG/g" Info.plist
        mkdir -p $DIR/rdm/bin/osx/release
        cd $DIR/rdm/bin/osx/release
        touch setup.cfg
        /bin/cat <<EOM >setup.cfg
        [install]
        prefix=
        EOM
        pip3 install -t ./ -r ../../../src/py/requirements.txt --upgrade
        cd $DIR/rdm/src
        sed -i '' '/CONFIG-=app_bundle/d' rdm.pro
        qmake -v
        qmake CONFIG-=debug CONFIG+=sdk_no_version_check
        make -s -j 8

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
